### PR TITLE
Several updates to script, tests and meta data.

### PR DESCRIPTION
**Pull request by bhamodi**
Hey @jdcataldo,

Updated quite a bit of things in this PR. I ran all tests and they all passed. :+1: 
Changelog:

- Updated jshint config.
- Applied lint fixes and made formatting consistent throughout the codebase.
- Updated licenses to 2015.
- Updated dependencies.
- Fixed misconfigured package.json file (license and git repo properties)
  - Removed deprecated peer dependency.

### CODE REVIEW

**Comment by jdcataldo** [comment]
Can you revert the package.json? Only grunt should be a peerDependency of this.

**Comment by bhamodi** [comment]
@jdcataldo - peer dependencies are being deprecated in npm v3. (See this thread: https://github.com/webpack/url-loader/issues/12)

Peer dependencies need to become explicit dependencies now, so that is why I made this change.

**Comment by jdcataldo** [comment]
They will still be supported, they just won't be auto-installed. Also why are some of the devDependencies that are only used for local testing moved to peerDependencies?

**Comment by bhamodi** [comment]
@jdcataldo - they aren't moved there, it's just that the git diff looks funny. Check it out in split mode:
screen shot 2015-07-29 at 9 50 56 am

**Comment by jdcataldo** [comment]
Sure. The only change I would want to keep to the package.json is the url and the license change. Everything else I would prefer to keep as is.

**Comment by bhamodi** [comment]
Hey @jdcataldo - so I just reverted the grunt peer dependency change. But I would still recommend to keep the remaining package updates. What do you think? :)

**Comment by jdcataldo** [comment]
The grunt peerDependency is still a newer version that what I had which means people on anything less than 0.4.5 will have to upgrade. The other modules don't really need an upgrade as they are just for testing purposes. I am fine with jshint/formatting fixes.

**Comment by bhamodi** [comment]
Alright, done.

**Comment by bhamodi** [comment]
@jdcataldo

**Comment by bhamodi** [comment]
@jdcataldo - could we merge this in now? :+1:

**Comment by bhamodi** [comment]
@jdcataldo - ready to merge.

**Comment by jdcataldo** [comment]
Switched from jshint to eslint. Closing this out.

**Pull request closed without merging**
